/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElAside: typeof import('element-plus/es')['ElAside']
        ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
        ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElCol: typeof import('element-plus/es')['ElCol']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElDropdown: typeof import('element-plus/es')['ElDropdown']
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
        ElHeader: typeof import('element-plus/es')['ElHeader']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElImage: typeof import('element-plus/es')['ElImage']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElMain: typeof import('element-plus/es')['ElMain']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
        ElPagination: typeof import('element-plus/es')['ElPagination']
        ElRow: typeof import('element-plus/es')['ElRow']
        ElTable: typeof import('element-plus/es')['ElTable']
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
        ElTabPane: typeof import('element-plus/es')['ElTabPane']
        ElTabs: typeof import('element-plus/es')['ElTabs']
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
        HomeComponent: typeof import('./src/components/Home/HomeComponent.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        StoreComponent: typeof import('./src/components/Store/StoreComponent.vue')['default']
        UserComponent: typeof import('./src/components/User/UserComponent.vue')['default']
    }
}
